In [1]:
import pandas as pd
import numpy as np

# 處理 Option IV Data: 日頻率改為月頻率、缺失值填補與刪除

In [2]:
option_iv = pd.read_pickle('option_iv.pickle')

option_iv['date'] = pd.to_datetime(option_iv['date'])
option_iv['year_month'] = option_iv['date'].dt.to_period('M')

target = ['ATMC_IV', 'OTMP_IV', 'RVol', 'IVol', 'CVol', 'PVol']
mean = ['ATMC_IV_mean', 'OTMP_IV_mean', 'RVol_mean', 'IVol_mean', 'CVol_mean', 'PVol_mean']

# 計算每月平均
option_iv[mean] = option_iv.groupby(['cusip', 'year_month'])[target].transform('mean')


option_iv = option_iv[['year_month', 'cusip', 
                       'ATMC_IV_mean', 'OTMP_IV_mean', 
                       'RVol_mean', 'IVol_mean', 'CVol_mean', 'PVol_mean']]

option_iv = option_iv.drop_duplicates().sort_values(['year_month', 'cusip'])
option_iv.rename(columns = {'cusip':'CUSIP'}, inplace = True)

# 向後平移一個月
option_iv[mean] = option_iv.groupby('CUSIP')[mean].shift(1)

# forward fill nan
option_iv = option_iv.groupby('CUSIP').\
            apply(lambda x : x.fillna(method='ffill')).\
            reset_index(drop = True).dropna()

# Merge All X Variables

In [3]:
chmom = pd.read_pickle('chmom.pickle')
dolvol = pd.read_pickle('dolvol.pickle')
idiovol = pd.read_pickle('idiovol.pickle')
indmom = pd.read_pickle('indmom.pickle').drop(columns = ['SICCD', 'industry'])
maxret = pd.read_pickle('maxret.pickle')
momentum = pd.read_pickle('momentum.pickle')
mvel1 = pd.read_pickle('mvel1.pickle')
retvol = pd.read_pickle('retvol.pickle')

In [4]:
df_list = [option_iv, chmom, dolvol, idiovol, indmom, maxret, momentum, mvel1, retvol]
result = df_list[0]

for df in df_list[1:]:
    result = pd.merge(result, df, on=['CUSIP', 'year_month'], how = 'outer')
    
result = result.sort_values(['year_month', 'CUSIP']).dropna().reset_index(drop = True)

result

,year_month,CUSIP,ATMC_IV_mean,OTMP_IV_mean,RVol_mean,IVol_mean,CVol_mean,PVol_mean,chmom,dolvol,Idiovol,indmom,maxret,mom1m,mom12m,mvel1,retvol
0,1996-02,00154710,0.257208,0.323483,0.220686,0.262732,0.252607,0.323483,-0.023687,18.991104,0.0004,0.026554,0.056604,0.014599,0.390693,0.000144,0.016252
1,1996-02,00253A30,0.729026,0.750821,0.585949,0.724408,0.739340,0.768624,-0.445465,18.030884,0.001202,0.037903,0.089686,0.321078,2.898839,0.000041,0.038457
2,1996-02,00282410,0.251968,0.316617,0.252172,0.254476,0.249830,0.261010,-0.069666,21.816896,0.000208,0.055842,0.046729,0.026363,0.227798,0.005134,0.018136
3,1996-02,00507V10,0.839863,0.690596,1.202595,0.724976,0.754422,0.695530,-0.210886,18.654159,0.002962,0.026398,0.162500,0.227274,0.969375,0.000024,0.083034
4,1996-02,00724F10,0.652997,0.660591,1.144925,0.645635,0.651295,0.639781,-1.585955,22.395970,0.001576,0.026398,0.043771,-0.450846,0.179937,0.000483,0.069826
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426313,2022-12,98980G10,0.786827,0.810571,0.795626,0.727191,0.726468,0.727443,0.430491,23.328851,0.001305,0.039053,0.145118,-0.134005,-0.615382,0.000497,0.052458
426314,2022-12,98980L10,0.761900,0.776282,0.670520,0.673678,0.672042,0.675726,0.193744,23.306643,0.000912,0.039053,0.144627,-0.095997,-0.643208,0.000498,0.051019
426315,2022-12,98981710,0.648493,0.683476,0.662870,0.616924,0.608556,0.624028,-0.008376,19.366867,0.000617,0.074891,0.131376,0.036559,-0.491915,0.000012,0.043085
426316,2022-12,98983V10,0.667777,0.778182,0.572776,0.635922,0.625587,0.645638,0.245538,19.445979,0.000647,0.039053,0.153191,-0.001301,-0.612316,0.000024,0.039937
426317,2022-12,98986M10,0.578933,0.646118,0.695320,0.548735,0.542207,0.553990,1.249419,18.310443,0.001615,0.039053,0.076316,0.203510,0.190592,0.000013,0.029264

In [19]:
result.columns

Index(['year_month', 'CUSIP', 'ATMC_IV_mean', 'OTMP_IV_mean', 'RVol_mean',
       'IVol_mean', 'CVol_mean', 'PVol_mean', 'chmom', 'dolvol', 'Idiovol',
       'indmom', 'maxret', 'mom1m', 'mom12m', 'mvel1', 'retvol'],
      dtype='object')

In [23]:
def normalize(group):
    # Your custom normalization logic goes here
    return (group - group.min()) / (group.max() - group.min())

# Select only the columns you want to normalize (excluding 'year_month' and 'CUSIP')
cols_to_normalize = ['ATMC_IV_mean', 'OTMP_IV_mean', 'RVol_mean','IVol_mean', 'CVol_mean', 'PVol_mean',
                     'chmom', 'dolvol', 'Idiovol', 'indmom', 'maxret', 'mom1m', 'mom12m', 'mvel1', 'retvol']

# Group by 'year_month' and apply the custom normalization function to each group
norm = result.groupby('year_month')[cols_to_normalize].apply(normalize).reset_index().drop(columns = 'level_1')
norm['CUSIP'] = result['CUSIP']


column_order = ['year_month', 'CUSIP'] + cols_to_normalize
norm = norm[column_order]

norm

,year_month,CUSIP,ATMC_IV_mean,OTMP_IV_mean,RVol_mean,IVol_mean,CVol_mean,PVol_mean,chmom,dolvol,Idiovol,indmom,maxret,mom1m,mom12m,mvel1,retvol
0,1996-02,00154710,0.103079,0.13508,0.068372,0.110335,0.100626,0.170172,0.750294,0.305409,0.057332,0.621315,0.183914,0.553984,0.102541,0.006568,0.092558
1,1996-02,00253A30,0.573521,0.545357,0.255736,0.603511,0.616061,0.640147,0.696998,0.165227,0.200661,0.758034,0.311045,0.828694,0.350606,0.001287,0.278413
2,1996-02,00282410,0.097854,0.128488,0.084524,0.101516,0.097686,0.104214,0.744484,0.717942,0.022986,0.974135,0.145965,0.564528,0.086431,0.262388,0.108329
3,1996-02,00507V10,0.684034,0.487536,0.572048,0.604117,0.632032,0.562976,0.726639,0.256219,0.5154,0.619444,0.590862,0.744614,0.159775,0.0004,0.651524
4,1996-02,00724F10,0.497713,0.458729,0.542466,0.519363,0.522824,0.504117,0.552887,0.802481,0.26753,0.619444,0.134598,0.136784,0.081697,0.02396,0.540971
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426313,2022-12,98980G10,0.429959,0.3972,0.103654,0.287921,0.283386,0.279135,0.289413,0.680486,0.021415,0.189687,0.067773,0.200569,0.045052,0.008343,0.111908
426314,2022-12,98980L10,0.4157,0.378718,0.087187,0.265696,0.261114,0.257618,0.265267,0.678716,0.01495,0.189687,0.067542,0.21382,0.041541,0.008372,0.108815
426315,2022-12,98981710,0.350828,0.328698,0.08618,0.242124,0.235134,0.23611,0.244653,0.364725,0.010094,0.44567,0.061311,0.26003,0.060627,0.000173,0.091758
426316,2022-12,98983V10,0.361858,0.379742,0.074322,0.250014,0.242104,0.245101,0.27055,0.37103,0.010587,0.189687,0.071569,0.246832,0.045438,0.000388,0.08499
426317,2022-12,98986M10,0.311037,0.308562,0.090451,0.213802,0.207983,0.206971,0.372937,0.28053,0.026523,0.189687,0.035418,0.318232,0.146726,0.000192,0.062046

**Result 的資料都已經平移過，ex: year_month=1996-02 對應到的是 1996-01 資料的計算結果**

# y: Monthly Return

In [6]:
data = pd.read_pickle('CRSP.pickle')
df = data[['date', 'CUSIP', 'RET', 'ewretd']].copy()

df['RET'] = pd.to_numeric(df['RET'], errors='coerce')
df['ewretd'] = pd.to_numeric(df['ewretd'], errors='coerce')
df.dropna(subset=['RET', 'ewretd'], inplace=True)

df['exret'] = df['RET']-df['ewretd']
df['date'] = pd.to_datetime(df['date'])
df['year_month'] = df['date'].dt.to_period('M')

df = df.sort_values(by=['CUSIP', 'year_month'])
df['log_exret'] = np.log(df['exret']+1)

month_ret = df.groupby(['CUSIP', 'year_month'])['log_exret'].sum().rename('month_log_exret').reset_index()
month_ret['month_exret'] = np.exp(month_ret['month_log_exret'])-1
month_ret = month_ret[['CUSIP', 'year_month', 'month_exret']]

/Users/leeyuihsin/Library/jupyterlab-desktop/jlab_server/lib/python3.8/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [24]:
month_ret

            CUSIP year_month  month_exret
0        00030710    2014-10     0.145985
1        00030710    2014-11     0.326061
2        00030710    2014-12     0.071002
3        00030710    2015-01    -0.158275
4        00030710    2015-02     0.338927
...           ...        ...          ...
1623918  Y2718360    2008-04    -0.031330
1623919  Y2718360    2008-05    -0.019840
1623920  Y2718360    2008-06     0.088156
1623921  Y2718360    2008-07    -0.009111
1623922  Y2718360    2008-08    -0.084829

[1623923 rows x 3 columns]

In [25]:
merged = pd.merge(norm, month_ret, on=['CUSIP', 'year_month'], how = 'inner')
merged.to_csv('ready.csv')
merged

,year_month,CUSIP,ATMC_IV_mean,OTMP_IV_mean,RVol_mean,IVol_mean,CVol_mean,PVol_mean,chmom,dolvol,Idiovol,indmom,maxret,mom1m,mom12m,mvel1,retvol,month_exret
0,1996-02,00154710,0.103079,0.13508,0.068372,0.110335,0.100626,0.170172,0.750294,0.305409,0.057332,0.621315,0.183914,0.553984,0.102541,0.006568,0.092558,0.001597
1,1996-02,00253A30,0.573521,0.545357,0.255736,0.603511,0.616061,0.640147,0.696998,0.165227,0.200661,0.758034,0.311045,0.828694,0.350606,0.001287,0.278413,-0.138899
2,1996-02,00282410,0.097854,0.128488,0.084524,0.101516,0.097686,0.104214,0.744484,0.717942,0.022986,0.974135,0.145965,0.564528,0.086431,0.262388,0.108329,-0.057942
3,1996-02,00507V10,0.684034,0.487536,0.572048,0.604117,0.632032,0.562976,0.726639,0.256219,0.5154,0.619444,0.590862,0.744614,0.159775,0.0004,0.651524,0.048120
4,1996-02,00724F10,0.497713,0.458729,0.542466,0.519363,0.522824,0.504117,0.552887,0.802481,0.26753,0.619444,0.134598,0.136784,0.081697,0.02396,0.540971,-0.055008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426313,2022-12,98980G10,0.429959,0.3972,0.103654,0.287921,0.283386,0.279135,0.289413,0.680486,0.021415,0.189687,0.067773,0.200569,0.045052,0.008343,0.111908,-0.350278
426314,2022-12,98980L10,0.4157,0.378718,0.087187,0.265696,0.261114,0.257618,0.265267,0.678716,0.01495,0.189687,0.067542,0.21382,0.041541,0.008372,0.108815,-0.311701
426315,2022-12,98981710,0.350828,0.328698,0.08618,0.242124,0.235134,0.23611,0.244653,0.364725,0.010094,0.44567,0.061311,0.26003,0.060627,0.000173,0.091758,-0.266589
426316,2022-12,98983V10,0.361858,0.379742,0.074322,0.250014,0.242104,0.245101,0.27055,0.37103,0.010587,0.189687,0.071569,0.246832,0.045438,0.000388,0.08499,-0.353136
426317,2022-12,98986M10,0.311037,0.308562,0.090451,0.213802,0.207983,0.206971,0.372937,0.28053,0.026523,0.189687,0.035418,0.318232,0.146726,0.000192,0.062046,-0.211558

In [12]:
(merged['year_month']>='2018').sum()

101717